# Generated by Django 5.2.4 on 2025-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
